title: <p align="center"> Nga Tran </p>

logo: "/images/logo2.png?raw=true"

description:
  <p align="center">
  <a href="https://medium.com/@tpnga95">Medium</a> |
  <a href="https://www.linkedin.com/in/nga-phuong-tran-260457140/">LinkedIn</a> |
  <a href="https://github.com/tpnga95?tab=repositories">GitHub</a>
  </p>
  
  <p align="justify">
  Hi, I am pursing MS degree in Data Science at Aston University, UK.
  <br><br>
  I had over 5 years of experience working in the Data Science field in a fintech company with strong focus on delivering customer-centric analytics. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
